export const ERROR_CONSULTA = 'ERROR_CONSULTA'
export const ADD_DATA = 'ADD_DATA'
export const CLEAR_DATA = 'CLEAR_DATA'
export const FIND_DATA = 'FIND_DATA'
export const CREATE_DATA = 'CREATE_DATA'
export const CLEAR_INITIAL_DATA = 'CLEAR_INITIAL_DATA'